services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env
    environment:
      # host.docker.internal = Windows/Mac-ийн локал машин руу холбогдоно
      DB_HOST: host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  proxy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - web

volumes:
  static_volume:
  caddy_data:
  caddy_config:
