"""
Shop app URLs
"""
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/sales-report/', views.sales_report, name='sales_report'),
    path('dashboard/supply/unloading/', views.unloading, name='unloading'),
    path('dashboard/supply/unloading/export/', views.unloading_export, name='unloading_export'),
    path('dashboard/data-sync/', views.data_sync, name='data_sync'),
    path('dashboard/data-sync/start/', views.data_sync_start, name='data_sync_start'),
    path('dashboard/data-sync/status/', views.data_sync_status, name='data_sync_status'),
    path('dashboard/data-sync/views/', views.data_sync_views, name='data_sync_views'),
    path('dashboard/sales-report/export/', views.sales_report_export, name='sales_report_export'),
    path('dashboard/sales-report/customers/', views.sales_report_customers, name='sales_report_customers'),
    path('dashboard/sales-report-ht/', views.sales_report_ht, name='sales_report_ht'),
    path('dashboard/sales-report-ht/dashboard/', views.sales_report_ht_dashboard, name='sales_report_ht_dashboard'),
    path('dashboard/sales-report-ht/breakdown/', views.sales_report_ht_breakdown, name='sales_report_ht_breakdown'),
    path('dashboard/sales-report-ht/export/', views.sales_report_ht_export, name='sales_report_ht_export'),
    path('dashboard/purchase-report/', views.purchase_report, name='purchase_report'),
    path('dashboard/delivery-report/', views.delivery_report, name='delivery_report'),
    path('dashboard/expense-report/', views.expense_report, name='expense_report'),
    path('dashboard/receivables/', views.recpay_report, {'kind': 'receivable'}, name='receivable_report'),
    path('dashboard/receivables/ledger/', views.recpay_ledger, {'kind': 'receivable'}, name='receivable_ledger'),
    path('dashboard/receivables/export/', views.recpay_export, {'kind': 'receivable'}, name='receivable_export'),
    path('dashboard/payables/', views.recpay_report, {'kind': 'payable'}, name='payable_report'),
    path('dashboard/payables/ledger/', views.recpay_ledger, {'kind': 'payable'}, name='payable_ledger'),
    path('dashboard/payables/export/', views.recpay_export, {'kind': 'payable'}, name='payable_export'),
    path('dashboard/expense-report-by-year/', views.expense_report_by_year, name='expense_report_by_year'),
    path('dashboard/expense-transaction-detail/', views.expense_transaction_detail, name='expense_transaction_detail'),
    path('dashboard/inventory/', views.inventory_report, name='inventory_report'),
    path('dashboard/item-prices/', views.item_prices, name='item_prices'),
    path('dashboard/item-prices/export/', views.item_prices_export, name='item_prices_export'),
    path('dashboard/item-costs/', views.item_costs, name='item_costs'),
    path('dashboard/item-costs/export/', views.item_costs_export, name='item_costs_export'),
    path('dashboard/meals/', views.meal_list, name='meal_list'),
    path('dashboard/meals/new/', views.meal_edit, name='meal_create'),
    path('dashboard/meals/<int:pk>/edit/', views.meal_edit, name='meal_edit'),
    path('dashboard/meals/<int:pk>/delete/', views.meal_delete, name='meal_delete'),
    path('dashboard/meals/<int:pk>/toggle-active/', views.meal_toggle_active, name='meal_toggle_active'),
    path('dashboard/meals/cycle-settings/', views.meal_cycle_settings_update, name='meal_cycle_settings_update'),
    path('dashboard/meals/material-calc/', views.meal_material_calc, name='meal_material_calc'),
    path('dashboard/meal-attendance/', views.meal_attendance_list, name='meal_attendance_list'),
    path('dashboard/meal-attendance/summary/', views.meal_attendance_summary, name='meal_attendance_summary'),
    path('dashboard/meal-attendance/new/', views.meal_attendance_form, name='meal_attendance_create'),
    path('dashboard/meal-attendance/<int:pk>/edit/', views.meal_attendance_form, name='meal_attendance_edit'),
    path('dashboard/meal-attendance/<int:pk>/delete/', views.meal_attendance_delete, name='meal_attendance_delete'),
    path('dashboard/hr/attendance/', views.attendance_calc, name='attendance_calc'),
    path('dashboard/hr/attendance/export/', views.attendance_export, name='attendance_export'),
    path('dashboard/hr/attendance/filter/', views.attendance_filter_save, name='attendance_filter_save'),
    path('dashboard/hr/attendance/sync/', views.attendance_sync, name='attendance_sync'),
    path('dashboard/hr/attendance/sync-merchandiser/', views.attendance_sync_merchandiser, name='attendance_sync_merchandiser'),
    path('dashboard/hr/attendance/save/', views.attendance_save, name='attendance_save'),
    path('dashboard/hr/attendance/delete/', views.attendance_delete, name='attendance_delete'),
    path('dashboard/hr/attendance/add/', views.attendance_add, name='attendance_add'),
    path('dashboard/hr/attendance/hide/', views.attendance_hide, name='attendance_hide'),
    path('dashboard/hr/attendance/bulk-delete/', views.attendance_bulk_delete, name='attendance_bulk_delete'),
    path('dashboard/hr/attendance/position-settings/', views.attendance_position_settings, name='attendance_position_settings'),
    path('dashboard/hr/timesheet/', views.timesheet, name='timesheet'),
    path('dashboard/hr/timesheet/export/', views.timesheet_export, name='timesheet_export'),
    path('dashboard/hr/payroll/card/', views.payroll, {'sheet': 'card'}, name='payroll_card'),
    path('dashboard/hr/payroll/cash/', views.payroll, {'sheet': 'cash'}, name='payroll_cash'),
    path('dashboard/hr/payroll/card/export/', views.payroll_export, {'sheet': 'card'}, name='payroll_card_export'),
    path('dashboard/hr/payroll/cash/export/', views.payroll_export, {'sheet': 'cash'}, name='payroll_cash_export'),
    path('dashboard/hr/payroll/settings/', views.payroll_settings, name='payroll_settings'),
    path('dashboard/hr/payroll/report/', views.payroll_report, name='payroll_report'),
    path('dashboard/hr/payroll/cash-accounts/', views.cash_bank_accounts, name='cash_bank_accounts'),
    path('dashboard/hr/payroll/sales-bonus/', views.sales_bonus, name='sales_bonus'),
    path('dashboard/hr/payroll/advance/card/', views.payroll_advance, {'sheet': 'card'}, name='payroll_advance_card'),
    path('dashboard/hr/payroll/advance/cash/', views.payroll_advance, {'sheet': 'cash'}, name='payroll_advance_cash'),
    path('dashboard/hr/employee-fingerprint/', views.employee_fingerprint, name='employee_fingerprint'),
    path('profile/', views.profile, name='profile'),
    path('profile/attendance/', views.my_attendance, name='my_attendance'),
    path('profile/payroll/', views.my_payroll, name='my_payroll'),
    path('profile/sales-bonus/', views.my_sales_bonus, name='my_sales_bonus'),
    path('settings/menu-permissions/', views.menu_permission_config, name='menu_permission_config'),
    path('api/ai-chat/', views.ai_chat_message, name='ai_chat_message'),
    path('api/product-stock/', views.product_stock_lookup, name='product_stock_lookup'),
    path('products/', views.product_list, name='products'),
    path('products/<str:pk>/', views.product_detail, name='product_detail'),
    path('products/<str:pk>/edit/', views.product_edit, name='product_edit'),
    
    # Auth
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='shop/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    # Password Reset
    path('password-reset/', 
         auth_views.PasswordResetView.as_view(
             template_name='shop/password_reset.html',
             email_template_name='shop/password_reset_email.txt',
             html_email_template_name='shop/password_reset_email.html',
             subject_template_name='shop/password_reset_subject.txt',
             success_url='/password-reset/done/'
         ), 
         name='password_reset'),
    path('password-reset/done/', 
         auth_views.PasswordResetDoneView.as_view(template_name='shop/password_reset_done.html'), 
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(
             template_name='shop/password_reset_confirm.html',
             success_url='/password-reset-complete/'
         ), 
         name='password_reset_confirm'),
    path('password-reset-complete/', 
         auth_views.PasswordResetCompleteView.as_view(template_name='shop/password_reset_complete.html'), 
         name='password_reset_complete'),
]

