# Generated by Django 6.0 on 2025-12-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDataCustomer',
            fields=[
                ('id', models.TextField(db_column='Id', primary_key=True, serialize=False)),
                ('pkid', models.BigIntegerField(blank=True, db_column='PkId', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('registrynumber', models.TextField(blank=True, db_column='RegistryNumber', null=True)),
                ('distributionchannelname', models.TextField(blank=True, db_column='DistributionChannelName', null=True)),
                ('customerlevel', models.TextField(blank=True, db_column='CustomerLevel', null=True)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
                ('paymenttype', models.TextField(blank=True, db_column='PaymentType', null=True)),
                ('regionname', models.TextField(blank=True, db_column='RegionName', null=True)),
                ('loanlimit', models.FloatField(blank=True, db_column='LoanLimit', null=True)),
                ('activestatus', models.TextField(blank=True, db_column='ActiveStatus', null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
            ],
            options={
                'verbose_name': 'Харилцагч',
                'verbose_name_plural': 'Харилцагчид',
                'db_table': 'OpenDataCustomer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpenDataEmployee',
            fields=[
                ('id', models.TextField(db_column='Id', primary_key=True, serialize=False)),
                ('pkid', models.BigIntegerField(blank=True, db_column='PkId', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('registrynumber', models.TextField(blank=True, db_column='RegistryNumber', null=True)),
                ('departmentname', models.TextField(blank=True, db_column='DepartmentName', null=True)),
                ('positionname', models.TextField(blank=True, db_column='PositionName', null=True)),
                ('mobilenumber', models.TextField(blank=True, db_column='MobileNumber', null=True)),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
                ('hiredate', models.DateField(blank=True, db_column='HireDate', null=True)),
                ('basesalary', models.FloatField(blank=True, db_column='BaseSalary', null=True)),
                ('isreclusion', models.TextField(blank=True, db_column='IsReclusion', null=True)),
            ],
            options={
                'verbose_name': 'Ажилчин',
                'verbose_name_plural': 'Ажилчид',
                'db_table': 'OpenDataEmployee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpenDataInventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('documentpkid', models.BigIntegerField(blank=True, db_column='DocumentPkId', null=True)),
                ('documentdate', models.DateField(blank=True, db_column='DocumentDate', null=True)),
                ('documenttype', models.TextField(blank=True, db_column='DocumentType', null=True)),
                ('warehousename', models.TextField(blank=True, db_column='WarehouseName', null=True)),
                ('itemname', models.TextField(blank=True, db_column='ItemName', null=True)),
                ('brandname', models.TextField(blank=True, db_column='BrandName', null=True)),
                ('inqty', models.FloatField(blank=True, db_column='InQty', null=True)),
                ('outqty', models.FloatField(blank=True, db_column='OutQty', null=True)),
                ('endqty', models.FloatField(blank=True, db_column='EndQty', null=True)),
                ('unitcost', models.FloatField(blank=True, db_column='UnitCost', null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
            ],
            options={
                'verbose_name': 'Нөөцийн хөдөлгөөн',
                'verbose_name_plural': 'Нөөцийн хөдөлгөөнүүд',
                'db_table': 'OpenDataInventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpenDataItem',
            fields=[
                ('id', models.TextField(db_column='Id', primary_key=True, serialize=False)),
                ('pkid', models.BigIntegerField(blank=True, db_column='PkId', null=True)),
                ('barcode', models.TextField(blank=True, db_column='Barcode', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('qtyinpackage', models.FloatField(blank=True, db_column='QtyInPackage', null=True)),
                ('baseprice', models.FloatField(blank=True, db_column='BasePrice', null=True)),
                ('saleprice', models.FloatField(blank=True, db_column='SalePrice', null=True)),
                ('standardunitcost', models.FloatField(blank=True, db_column='StandardUnitCost', null=True)),
                ('itemcategoryname', models.TextField(blank=True, db_column='ItemCategoryName', null=True)),
                ('measurename', models.TextField(blank=True, db_column='MeasureName', null=True)),
                ('manufacturername', models.TextField(blank=True, db_column='ManufacturerName', null=True)),
                ('brandname', models.TextField(blank=True, db_column='BrandName', null=True)),
                ('activestatus', models.TextField(blank=True, db_column='ActiveStatus', null=True)),
            ],
            options={
                'verbose_name': 'Бүтээгдэхүүн',
                'verbose_name_plural': 'Бүтээгдэхүүнүүд',
                'db_table': 'OpenDataItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpenDataPurchase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('documentpkid', models.BigIntegerField(blank=True, db_column='DocumentPkId', null=True)),
                ('documentnumber', models.TextField(blank=True, db_column='DocumentNumber', null=True)),
                ('documentdate', models.DateField(blank=True, db_column='DocumentDate', null=True)),
                ('vendorname', models.TextField(blank=True, db_column='VendorName', null=True)),
                ('warehousename', models.TextField(blank=True, db_column='WarehouseName', null=True)),
                ('itemname', models.TextField(blank=True, db_column='ItemName', null=True)),
                ('qty', models.FloatField(blank=True, db_column='Qty', null=True)),
                ('unitcost', models.FloatField(blank=True, db_column='UnitCost', null=True)),
                ('amount', models.FloatField(blank=True, db_column='Amount', null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
            ],
            options={
                'verbose_name': 'Худалдан авалт',
                'verbose_name_plural': 'Худалдан авалтууд',
                'db_table': 'OpenDataPurchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpenDataSale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('documentpkid', models.BigIntegerField(blank=True, db_column='DocumentPkId', null=True)),
                ('documentnumber', models.TextField(blank=True, db_column='DocumentNumber', null=True)),
                ('documentdate', models.DateField(blank=True, db_column='DocumentDate', null=True)),
                ('warehousename', models.TextField(blank=True, db_column='WarehouseName', null=True)),
                ('itemname', models.TextField(blank=True, db_column='ItemName', null=True)),
                ('brandname', models.TextField(blank=True, db_column='BrandName', null=True)),
                ('sellername', models.TextField(blank=True, db_column='SellerName', null=True)),
                ('customername', models.TextField(blank=True, db_column='CustomerName', null=True)),
                ('distributionchannelname', models.TextField(blank=True, db_column='DistributionChannelName', null=True)),
                ('qty', models.FloatField(blank=True, db_column='Qty', null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('payamount', models.FloatField(blank=True, db_column='PayAmount', null=True)),
                ('unitcost', models.FloatField(blank=True, db_column='UnitCost', null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
            ],
            options={
                'verbose_name': 'Борлуулалт',
                'verbose_name_plural': 'Борлуулалтууд',
                'db_table': 'OpenDataSale',
                'managed': False,
            },
        ),
    ]
