"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config


def parse_csv_setting(value):
    """Split comma-separated env values and trim whitespace."""
    return [item.strip() for item in value.split(',') if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-p1#(#1rvuv@_px!as_33pvnym=ir3@4-se94ubsb5y5l!2huf_')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = parse_csv_setting(
    config(
        'ALLOWED_HOSTS',
        default='localhost,127.0.0.1,tae.mn,www.tae.mn,202.179.22.189',
    )
)

CSRF_TRUSTED_ORIGINS = parse_csv_setting(
    config(
        'CSRF_TRUSTED_ORIGINS',
        default='http://localhost,http://127.0.0.1,http://202.179.22.189,http://202.179.22.189:8000,http://tae.mn,http://www.tae.mn',
    )
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # Тоон форматлах (intcomma гэх мэт)
    
    # Local apps
    'shop',  # E-commerce frontend
    'datamigration',  # MSSQL -> PostgreSQL data migration
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.user_position',  # Хэрэглэгчийн албан тушаал
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Кэш - файл дээр: вэб сервер болон синк (import_views) процесс хуваалцана - синкийн дараа тайлангийн кэшийг
# урьдчилан бэлдэхэд (shop.services.sales_report.warm_cache)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': BASE_DIR / '.cache',
        'TIMEOUT': 3 * 60 * 60,
        'OPTIONS': {'MAX_ENTRIES': 3000},
    }
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='tae_db'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# Цаг бүртгэлийн хурууны хээ таних төхөөрөмж (ZKTeco)
ATTENDANCE_DEVICE_IP = config('ATTENDANCE_DEVICE_IP', default='192.168.0.201')
ATTENDANCE_DEVICE_PORT = config('ATTENDANCE_DEVICE_PORT', default=4370, cast=int)

# Цаг бүртгэлийн тооцооны хүснэгт олон ажилтан/өдрөөр том байж болох тул (мөр бүр ~11 талбар),
# JS талд зөвхөн засварласан мөрүүдийг л илгээдэг ч нөөц хамгаалалт болгож Django-гийн 1000
# гэсэн анхны хязгаарыг өсгөв (DATA_UPLOAD_MAX_NUMBER_FIELDS алдаа TooManyFieldsSent-с сэргийлнэ)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = config('LANGUAGE_CODE', default='mn-mn')

TIME_ZONE = config('TIME_ZONE', default='Asia/Ulaanbaatar')

USE_I18N = True

USE_TZ = True

# Number formatting - мянгачлал идэвхжүүлэх
USE_THOUSAND_SEPARATOR = True
NUMBER_GROUPING = 3  # 3 оронтой бүлэглэх
THOUSAND_SEPARATOR = ','  # Таслалаар ангилах


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication backends - зөвхөн имэйлээр нэвтрэх
AUTHENTICATION_BACKENDS = [
    'shop.backends.EmailBackend',
]

# Login/Logout redirect URLs
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login/'

# Proxy + cookie security settings (important for CSRF validation on deployed domains)
USE_X_FORWARDED_HOST = config('USE_X_FORWARDED_HOST', default=True, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SAMESITE = config('CSRF_COOKIE_SAMESITE', default='Lax')
SESSION_COOKIE_SAMESITE = config('SESSION_COOKIE_SAMESITE', default='Lax')

# Email configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='webmaster@localhost')

# AI чат - Anthropic Claude API-г Django-с шууд дуудна
ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY', default='')

