# Generated by Django 6.0 on 2025-12-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExtension',
            fields=[
                ('item_id', models.TextField(primary_key=True, serialize=False, unique=True, verbose_name='Бүтээгдэхүүний ID')),
                ('name_mn', models.CharField(blank=True, max_length=500, verbose_name='Монгол нэр')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, verbose_name='Үйлдвэрлэсэн улс')),
                ('qty_per_box', models.IntegerField(blank=True, null=True, verbose_name='Хайрцаг дахь тоо')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Нийлүүллэгч')),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Үндсэн зураг')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Зураг 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Зураг 3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
            ],
            options={
                'verbose_name': 'Бүтээгдэхүүний нэмэлт мэдээлэл',
                'verbose_name_plural': 'Бүтээгдэхүүний нэмэлт мэдээлэл',
                'db_table': 'shop_product_extension',
            },
        ),
    ]
