# Generated by Django 6.0 on 2025-12-11 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Утас')),
                ('is_employee', models.BooleanField(default=False, verbose_name='Ажилтан эсэх')),
                ('employee_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Ажилтны имэйл')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Хэрэглэгчийн профайл',
                'verbose_name_plural': 'Хэрэглэгчийн профайлууд',
                'db_table': 'shop_user_profile',
            },
        ),
    ]
