# Generated by Django 6.0 on 2026-02-12 05:26

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productextension',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.product_image_2_path, verbose_name='Зураг 2'),
        ),
        migrations.AlterField(
            model_name='productextension',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.product_image_3_path, verbose_name='Зураг 3'),
        ),
        migrations.AlterField(
            model_name='productextension',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.product_image_main_path, verbose_name='Үндсэн зураг'),
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(db_index=True, max_length=500, verbose_name='Барааны нэр')),
                ('brandname', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Брэнд')),
                ('tolgoit_qty', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Толгойт')),
                ('jijig_qty', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Жижиг')),
                ('altjin_qty', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Алтжин')),
                ('total_qty', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Нийт')),
                ('avg_unitcost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Дундаж өртөг')),
                ('tolgoit_date', models.DateField(blank=True, null=True, verbose_name='Толгойт огноо')),
                ('jijig_date', models.DateField(blank=True, null=True, verbose_name='Жижиг огноо')),
                ('altjin_date', models.DateField(blank=True, null=True, verbose_name='Алтжин огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
            ],
            options={
                'verbose_name': 'Барааны үлдэгдэл (snapshot)',
                'verbose_name_plural': 'Барааны үлдэгдэл (snapshots)',
                'db_table': 'inventory_snapshot',
                'indexes': [models.Index(fields=['itemname'], name='inventory_s_itemnam_c6963f_idx'), models.Index(fields=['brandname'], name='inventory_s_brandna_3e1b83_idx'), models.Index(fields=['-total_qty'], name='inventory_s_total_q_4b0d47_idx'), models.Index(fields=['updated_at'], name='inventory_s_updated_c03b70_idx')],
                'constraints': [models.UniqueConstraint(fields=('itemname',), name='unique_item_snapshot')],
            },
        ),
    ]
