# Generated by Django 6.0 on 2026-02-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productextension_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='distributor_id',
            field=models.TextField(blank=True, null=True, verbose_name='Түгээгчийн ID'),
        ),
    ]
