# Generated by Django 6.0 on 2026-09-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_userprofile_distributor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=200, verbose_name='Албан тушаал')),
                ('menu_key', models.CharField(max_length=100, verbose_name='Цэсний түлхүүр')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Харуулах эсэх')),
            ],
            options={
                'verbose_name': 'Цэсний эрх',
                'verbose_name_plural': 'Цэсний эрхүүд',
                'db_table': 'shop_menu_permission',
                'unique_together': {('position_name', 'menu_key')},
            },
        ),
    ]
