# Generated by Django 6.0 on 2026-09-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_menupermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(max_length=100, unique=True, verbose_name='Цэсний түлхүүр')),
                ('group_key', models.CharField(max_length=100, verbose_name='Бүлгийн түлхүүр')),
            ],
            options={
                'verbose_name': 'Цэсний бүлэглэлт',
                'verbose_name_plural': 'Цэсний бүлэглэлтүүд',
                'db_table': 'shop_menu_group_assignment',
            },
        ),
    ]
