# Generated by Django 6.0 on 2026-09-17 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_menugroupassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Дугаар')),
                ('name', models.CharField(max_length=200, verbose_name='Хоолны нэр')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
            ],
            options={
                'verbose_name': 'Хоол',
                'verbose_name_plural': 'Хоолны бүртгэл',
                'db_table': 'shop_meal',
                'ordering': ['number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50, verbose_name='Орцын барааны код')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Хэмжээ')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Нэгж')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='shop.meal', verbose_name='Хоол')),
            ],
            options={
                'verbose_name': 'Хоолны орц',
                'verbose_name_plural': 'Хоолны орцууд',
                'db_table': 'shop_meal_ingredient',
            },
        ),
    ]
