# Generated by Django 6.0 on 2026-09-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_meal_mealingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['meal_type', 'number', 'name'], 'verbose_name': 'Хоол', 'verbose_name_plural': 'Хоолны бүртгэл'},
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('1', '1-р хоол'), ('2', '2-р хоол')], default='1', max_length=1, verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Дугаар'),
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('meal_type', 'number')},
        ),
    ]
