# Generated by Django 6.0 on 2026-09-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_meal_options_meal_meal_type_alter_meal_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['number', 'meal_type', 'name'], 'verbose_name': 'Хоол', 'verbose_name_plural': 'Хоолны бүртгэл'},
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('1', '1-р хоол'), ('2', '2-р хоол'), ('3', 'Хачир')], default='1', max_length=1, verbose_name='Төрөл'),
        ),
    ]
