# Generated by Django 6.0 on 2026-09-18 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_meal_options_alter_meal_meal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Огноо')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
            ],
            options={
                'verbose_name': 'Хоол идэх бүртгэл',
                'verbose_name_plural': 'Хоол идэх бүртгэлүүд',
                'db_table': 'shop_meal_attendance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MealCycleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_date', models.DateField(verbose_name='Циклийн эхлэх огноо (1-р дугаартай өдөр)')),
            ],
            options={
                'verbose_name': 'Хоолны циклийн тохиргоо',
                'verbose_name_plural': 'Хоолны циклийн тохиргоо',
                'db_table': 'shop_meal_cycle_settings',
            },
        ),
        migrations.CreateModel(
            name='MealAttendanceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Нэр')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Дараалал')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='shop.mealattendance')),
            ],
            options={
                'verbose_name': 'Хоол идэх хүний нэр',
                'verbose_name_plural': 'Хоол идэх хүмүүсийн нэрс',
                'db_table': 'shop_meal_attendance_name',
                'ordering': ['order', 'id'],
            },
        ),
    ]
