# Generated by Django 6.0 on 2026-09-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_mealattendance_mealcyclesettings_mealattendancename'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcyclesettings',
            name='effective_from',
            field=models.DateField(blank=True, help_text='Тохируулахад сонгосон огноо. Үүнээс өмнөх огноонд хоол харагдахгүй.', null=True, verbose_name='Хэрэгжиж эхэлсэн огноо'),
        ),
    ]
