# Generated by Django 6.0 on 2026-09-21 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_mealcyclesettings_effective_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealNumberAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Дугаар')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='shop.meal')),
            ],
            options={
                'verbose_name': 'Хоолны дугаар',
                'verbose_name_plural': 'Хоолны дугаарууд',
                'db_table': 'shop_meal_number_assignment',
                'ordering': ['number'],
            },
        ),
    ]
