# Generated by Django 6.0 on 2026-09-21 06:17

from django.db import migrations


def copy_numbers_forward(apps, schema_editor):
    Meal = apps.get_model('shop', 'Meal')
    MealNumberAssignment = apps.get_model('shop', 'MealNumberAssignment')
    for meal in Meal.objects.exclude(number__isnull=True):
        MealNumberAssignment.objects.create(meal=meal, number=meal.number)


def copy_numbers_backward(apps, schema_editor):
    MealNumberAssignment = apps.get_model('shop', 'MealNumberAssignment')
    Meal = apps.get_model('shop', 'Meal')
    for assignment in MealNumberAssignment.objects.all():
        Meal.objects.filter(pk=assignment.meal_id).update(number=assignment.number)
    MealNumberAssignment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_mealnumberassignment'),
    ]

    operations = [
        migrations.RunPython(copy_numbers_forward, copy_numbers_backward),
    ]
