# Generated by Django 6.0 on 2026-09-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_copy_meal_numbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['meal_type', 'name'], 'verbose_name': 'Хоол', 'verbose_name_plural': 'Хоолны бүртгэл'},
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='number',
        ),
    ]
