# Generated by Django 6.0 on 2026-09-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_meal_options_alter_meal_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='change_comment',
            field=models.TextField(blank=True, verbose_name='Өөрчлөлтийн тайлбар'),
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients_changed',
            field=models.BooleanField(default=False, verbose_name='Орц сүүлд өөрчлөгдсөн эсэх'),
        ),
    ]
