# Generated by Django 6.0 on 2026-09-22 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_meal_change_comment_meal_ingredients_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealattendance',
            name='change_comment',
            field=models.TextField(blank=True, verbose_name='Өөрчлөлтийн тайлбар'),
        ),
        migrations.AddField(
            model_name='mealattendance',
            name='ingredients_changed',
            field=models.BooleanField(default=False, verbose_name='Орц стандарт жораас өөрчлөгдсөн эсэх'),
        ),
        migrations.CreateModel(
            name='MealAttendanceIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50, verbose_name='Орцын барааны код')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Хэмжээ')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Нэгж')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_overrides', to='shop.mealattendance')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_overrides', to='shop.meal')),
            ],
            options={
                'verbose_name': 'Өдрийн бодит орц',
                'verbose_name_plural': 'Өдрийн бодит орцууд',
                'db_table': 'shop_meal_attendance_ingredient',
            },
        ),
    ]
