# Generated by Django 6.0 on 2026-09-22 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_mealattendance_change_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='change_comment',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='ingredients_changed',
        ),
    ]
