# Generated by Django 6.0 on 2026-09-22 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_meal_change_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRawLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(db_index=True, max_length=50, verbose_name='Төхөөрөмжийн хэрэглэгчийн ID')),
                ('timestamp', models.DateTimeField(verbose_name='Цаг тэмдэглэсэн огноо')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='Төхөөрөмжийн статус')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Татсан огноо')),
            ],
            options={
                'verbose_name': 'Ирцийн түүхий бүртгэл',
                'verbose_name_plural': 'Ирцийн түүхий бүртгэлүүд',
                'db_table': 'shop_attendance_raw_log',
                'ordering': ['-timestamp'],
                'unique_together': {('device_user_id', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(db_index=True, max_length=50, verbose_name='Ажилтны код')),
                ('device_user_id', models.CharField(blank=True, max_length=50, verbose_name='Төхөөрөмжийн хэрэглэгчийн ID')),
                ('name', models.CharField(max_length=200, verbose_name='Нэр')),
                ('date', models.DateField(verbose_name='Огноо')),
                ('weekday', models.CharField(blank=True, max_length=20, verbose_name='Гариг')),
                ('arrived_time', models.CharField(blank=True, max_length=5, verbose_name='Ирсэн цаг')),
                ('left_time', models.CharField(blank=True, max_length=5, verbose_name='Тарсан цаг')),
                ('late_1_10', models.PositiveIntegerField(default=0, verbose_name='1-10 минут')),
                ('late_11_20', models.PositiveIntegerField(default=0, verbose_name='11-20 минут')),
                ('late_20_plus', models.PositiveIntegerField(default=0, verbose_name='20-с дээш минут')),
                ('total_late_minutes', models.PositiveIntegerField(default=0, verbose_name='Нийт хоцорсон минут')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Засварласан хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Цаг бүртгэлийн мөр',
                'verbose_name_plural': 'Цаг бүртгэлийн мөрүүд',
                'db_table': 'shop_attendance_record',
                'ordering': ['-date', 'name'],
                'unique_together': {('employee_code', 'date')},
            },
        ),
    ]
