# Generated by Django 6.0 on 2026-09-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_attendancerawlog_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='customer_name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Харилцагчийн нэр'),
        ),
        migrations.CreateModel(
            name='MerchandiserVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(db_index=True, max_length=50, verbose_name='Баримтын дугаар')),
                ('employee_code', models.CharField(db_index=True, max_length=50, verbose_name='Мерчандайзерийн код')),
                ('employee_name', models.CharField(blank=True, max_length=200, verbose_name='Мерчандайзерийн нэр')),
                ('customer_name', models.CharField(blank=True, max_length=500, verbose_name='Харилцагчийн нэр')),
                ('timestamp', models.DateTimeField(verbose_name='Огноо/цаг')),
                ('source_column', models.CharField(max_length=20, verbose_name='Эх сурвалж багана')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Импортолсон огноо')),
            ],
            options={
                'verbose_name': 'Мерчандайзерийн зочилсон түүхий бүртгэл',
                'verbose_name_plural': 'Мерчандайзерийн зочилсон түүхий бүртгэлүүд',
                'db_table': 'shop_merchandiser_visit_log',
                'ordering': ['-timestamp'],
                'unique_together': {('document_number', 'source_column')},
            },
        ),
    ]
