# Generated by Django 6.0 on 2026-09-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_attendancerecord_customer_name_merchandiservisitlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePositionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=200, unique=True, verbose_name='Албан тушаал')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Ажил эхлэх цаг')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
            ],
            options={
                'verbose_name': 'Албан тушаалын ажлын цагийн дүрэм',
                'verbose_name_plural': 'Албан тушаалын ажлын цагийн дүрмүүд',
                'db_table': 'shop_attendance_position_rule',
                'ordering': ['position_name'],
            },
        ),
    ]
