# Generated by Django 6.0 on 2026-09-22 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_seed_attendance_position_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Ажилтны код')),
                ('device_user_id', models.CharField(blank=True, max_length=50, verbose_name='Төхөөрөмжийн код')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Засварласан хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Ажилтны хурууны мэдээлэл',
                'verbose_name_plural': 'Ажилтны хурууны мэдээлэл',
                'db_table': 'shop_employee_fingerprint',
                'ordering': ['employee_code'],
            },
        ),
    ]
