# Generated by Django 6.0 on 2026-09-22 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_seed_employee_fingerprints_from_xlsx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeefingerprint',
            constraint=models.UniqueConstraint(condition=models.Q(('device_user_id', ''), _negated=True), fields=('device_user_id',), name='unique_nonblank_device_user_id'),
        ),
    ]
