# Generated by Django 6.0 on 2026-09-24 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_seed_my_attendance_menu_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_rate_1_10', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='1-10 минутын хоцролт (₮/минут)')),
                ('late_rate_11_20', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='11-20 минутын хоцролт (₮/минут)')),
                ('late_rate_21_30', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='21-30 минутын хоцролт (₮/минут)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
            ],
            options={
                'verbose_name': 'Хоног бүртгэлийн тохиргоо',
                'verbose_name_plural': 'Хоног бүртгэлийн тохиргоо',
                'db_table': 'shop_timesheet_setting',
            },
        ),
        migrations.AddField(
            model_name='attendancepositionrule',
            name='schedule_type',
            field=models.CharField(choices=[('weekdays', 'Бямбад ажилладаггүй'), ('saturday', 'Бямбад ажилладаг'), ('shift', 'Ээлжийн')], default='weekdays', max_length=20, verbose_name='Ажлын горим'),
        ),
        migrations.CreateModel(
            name='OrganizationHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Засварласан хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Байгууллагын амралтын өдөр',
                'verbose_name_plural': 'Байгууллагын амралтын өдрүүд',
                'db_table': 'shop_organization_holiday',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(db_index=True, max_length=50, verbose_name='Ажилтны код')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Он')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Сар')),
                ('required_days', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Ажиллавал зохих хоног')),
                ('leave_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Ээлжийн амралт (хоног)')),
                ('excused_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Чөлөөтэй хоног')),
                ('excused_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Цагийн чөлөө')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Засварласан хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Хоног бүртгэлийн гар утга',
                'verbose_name_plural': 'Хоног бүртгэлийн гар утгууд',
                'db_table': 'shop_timesheet_entry',
                'unique_together': {('employee_code', 'year', 'month')},
            },
        ),
    ]
