# Generated by Django 6.0 on 2026-09-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_seed_timesheet_menu_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepositionrule',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Эрэмбэ'),
        ),
    ]
