# Generated by Django 6.0 on 2026-09-24 04:33

from django.db import migrations, models

# Цаг бүртгүүлдэггүй албан тушаалууд - Хоног бүртгэлд ажилласан хоног = ажиллавал зохих хоног
WORKED_EQUALS_REQUIRED_POSITIONS = ['Ерөнхий захирал', 'Захирал', 'Гадаад харилцаа', 'Бусад']


def seed_worked_equals_required(apps, schema_editor):
    AttendancePositionRule = apps.get_model('shop', 'AttendancePositionRule')
    for position_name in WORKED_EQUALS_REQUIRED_POSITIONS:
        AttendancePositionRule.objects.update_or_create(
            position_name=position_name,
            defaults={'worked_equals_required': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_attendancepositionrule_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetentry',
            name='required_days',
        ),
        migrations.AddField(
            model_name='attendancepositionrule',
            name='worked_equals_required',
            field=models.BooleanField(default=False, verbose_name='Ажилласан хоног = ажиллавал зохих хоног'),
        ),
        # Буцаахад талбар өөрөө устах тул өгөгдлийн алхамд буцаах үйлдэл хэрэггүй
        migrations.RunPython(seed_worked_equals_required, migrations.RunPython.noop),
    ]
