# Generated by Django 6.0 on 2026-09-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_timesheet_worked_equals_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Устгасан'),
        ),
    ]
