# Generated by Django 6.0 on 2026-09-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_attendancerecord_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='required_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Ажиллавал зохих хоног (гараар)'),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='worked_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Ажилласан хоног (гараар)'),
        ),
    ]
