# Generated by Django 6.0 on 2026-09-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_timesheetentry_manual_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='saturday_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Бямбад ажилласан (гараар)'),
        ),
    ]
