# Generated by Django 6.0 on 2026-09-25 03:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_timesheetentry_saturday_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndsh_employee_rate', models.DecimalField(decimal_places=2, default=Decimal('11.5'), max_digits=5, verbose_name='НДШ ажилтан (%)')),
                ('ndsh_employer_rate', models.DecimalField(decimal_places=2, default=Decimal('12.5'), max_digits=5, verbose_name='НДШ байгууллага (%)')),
                ('ndsh_max_base', models.DecimalField(decimal_places=2, default=Decimal('7920000'), max_digits=14, verbose_name='НДШ ногдуулах дээд хэмжээ (₮)')),
                ('pit_rate', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5, verbose_name='ХХОАТ (%)')),
                ('saturday_hours_per_day', models.DecimalField(decimal_places=1, default=Decimal('6'), max_digits=4, verbose_name='Бямба гарагийн ажлын цаг')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
            ],
            options={
                'verbose_name': 'Цалин бодолтын тохиргоо',
                'verbose_name_plural': 'Цалин бодолтын тохиргоо',
                'db_table': 'shop_payroll_setting',
            },
        ),
        migrations.CreateModel(
            name='PayrollTaxCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_to', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сарын цалин (хүртэл, ₮)')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Хөнгөлөлт (₮)')),
            ],
            options={
                'verbose_name': 'ХХОАТ-ын хөнгөлөлтийн шат',
                'verbose_name_plural': 'ХХОАТ-ын хөнгөлөлтийн шатлал',
                'db_table': 'shop_payroll_tax_credit',
                'ordering': [models.OrderBy(models.F('income_to'), nulls_last=True)],
            },
        ),
        migrations.CreateModel(
            name='EmployeePayProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50, unique=True, verbose_name='Ажилтны код')),
                ('pay_type', models.CharField(blank=True, choices=[('card', 'Карт'), ('cash', 'Бэлэн'), ('mixed', 'Хосолсон')], max_length=10, verbose_name='Олгох хэлбэр')),
                ('card_base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Картын үндсэн цалин')),
                ('card_seniority_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Картын удаан жилийн нэмэгдэл')),
                ('cash_base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Бэлэн үндсэн цалин')),
                ('cash_seniority_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Бэлэн удаан жилийн нэмэгдэл')),
                ('ndsh_code', models.CharField(blank=True, max_length=20, verbose_name='НДШ-ийн код')),
                ('ndsh_employee_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='НДШ ажилтан (%)')),
                ('ndsh_employer_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='НДШ байгууллага (%)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Засварласан хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Ажилтны цалингийн мэдээлэл',
                'verbose_name_plural': 'Ажилчдын цалингийн мэдээлэл',
                'db_table': 'shop_employee_pay_profile',
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(db_index=True, max_length=50, verbose_name='Ажилтны код')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Он')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Сар')),
                ('sheet', models.CharField(choices=[('card', 'Карт'), ('cash', 'Бэлэн')], max_length=10, verbose_name='Хуудас')),
                ('saturday_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Бямбад ажилласан нэмэгдэл')),
                ('holiday_pay', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Амралтын мөнгө')),
                ('sales_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Нэмэгдэл цалин /Борлуулалт/')),
                ('transport', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Унааны мөнгө')),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Урьдчилгаа')),
                ('risk_fund', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Эрсдэлийн сан')),
                ('inventory_shortage', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Тооллогын дутагдал')),
                ('goods_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Барааны суутгал')),
                ('phone_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Ярианы төлбөр')),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Торгууль')),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Бусад суутгал')),
                ('sick_employer', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ХЧТА-н мөнгө байгууллага')),
                ('sick_fund', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ХЧТА-н мөнгө НД-с')),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Хуримтлал')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Засварласан хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Цалин бодолтын гар утга',
                'verbose_name_plural': 'Цалин бодолтын гар утгууд',
                'db_table': 'shop_payroll_entry',
                'unique_together': {('employee_code', 'year', 'month', 'sheet')},
            },
        ),
    ]
