# Generated by Django 6.0 on 2026-09-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_update_tax_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolltaxcredit',
            name='income_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сарын цалин, НДШ хассан (хүртэл, ₮)'),
        ),
    ]
