# Generated by Django 6.0 on 2026-09-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_payrolltaxcredit_income_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepayprofile',
            name='card_seniority_bonus',
        ),
        migrations.RemoveField(
            model_name='employeepayprofile',
            name='cash_seniority_bonus',
        ),
        migrations.RemoveField(
            model_name='payrollentry',
            name='risk_fund',
        ),
        migrations.AddField(
            model_name='employeepayprofile',
            name='card_shift_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Картын нэг гарын мөнгө'),
        ),
        migrations.AddField(
            model_name='employeepayprofile',
            name='cash_shift_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Бэлэн нэг гарын мөнгө'),
        ),
    ]
