# Generated by Django 6.0 on 2026-09-25 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_remove_employeepayprofile_card_seniority_bonus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepayprofile',
            name='card_base_salary',
        ),
        migrations.RemoveField(
            model_name='employeepayprofile',
            name='ndsh_code',
        ),
    ]
