# Generated by Django 6.0 on 2026-09-25 05:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_payprofile_from_employee_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollentry',
            name='saturday_bonus',
        ),
        migrations.AddField(
            model_name='employeepayprofile',
            name='saturday_bonus_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=5, verbose_name='Бямбын нэмэгдэл (%)'),
        ),
    ]
