# Generated by Django 6.0 on 2026-09-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_saturday_bonus_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='NdshCodeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='НДШ-ийн код')),
                ('employee_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='НДШ ажилтан (%)')),
                ('employer_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='НДШ байгууллага (%)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
            ],
            options={
                'verbose_name': 'НДШ-ийн кодын хувь',
                'verbose_name_plural': 'НДШ-ийн кодын хувь',
                'db_table': 'shop_ndsh_code_rate',
                'ordering': ['code'],
            },
        ),
    ]
