# Generated by Django 6.0 on 2026-09-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_ndsh_code_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayprofile',
            name='saturday_in_worked_days',
            field=models.BooleanField(default=True, verbose_name='Бямбыг ажилласан хоногт оруулах'),
        ),
    ]
