# Generated by Django 6.0 on 2026-09-25 06:13

from django.db import migrations, models


def to_position_default(apps, schema_editor):
    """Анхдагчаар орсон утгуудыг "тохируулаагүй" (None - албан тушаалын горимоор) болгоно.

    Зөвхөн албан тушаалын горимоос өөр утгатай (гараар өөрчилсөн) мөрүүд тусгайлан тохиргоо хэвээр үлдэнэ.
    """
    EmployeePayProfile = apps.get_model('shop', 'EmployeePayProfile')
    AttendancePositionRule = apps.get_model('shop', 'AttendancePositionRule')
    OpenDataEmployee = apps.get_model('datamigration', 'OpenDataEmployee')

    saturday_positions = set(
        AttendancePositionRule.objects.filter(schedule_type='saturday').values_list('position_name', flat=True)
    )
    positions = dict(OpenDataEmployee.objects.values_list('id', 'positionname'))
    for profile in EmployeePayProfile.objects.exclude(saturday_in_worked_days__isnull=True):
        position_default = positions.get(profile.employee_code) in saturday_positions
        if profile.saturday_in_worked_days == position_default or profile.saturday_in_worked_days:
            # True нь өмнөх хувилбарын анхдагч утга байсан тул тусгай тохиргоо гэж тооцохгүй
            profile.saturday_in_worked_days = None
            profile.save(update_fields=['saturday_in_worked_days'])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_saturday_in_worked_days'),
        ('datamigration', '0002_opendatageneralledger_opendatalandedcost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepayprofile',
            name='saturday_in_worked_days',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Бямбыг ажилласан хоногт оруулах'),
        ),
        migrations.RunPython(to_position_default, migrations.RunPython.noop),
    ]
