# Generated by Django 6.0 on 2026-09-25 07:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_saturday_in_worked_days_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollentry',
            name='transport',
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='transport_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=10, verbose_name='Унааны мөнгө (хоногт, ₮)'),
        ),
    ]
