# Generated by Django 6.0 on 2026-09-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_transport_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollentry',
            name='savings',
        ),
    ]
