# Generated by Django 6.0 on 2026-10-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_seed_sales_report_ht_for_sales_reps'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timesheetentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='position_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Албан тушаал (тухайн өдөр)'),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='position_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Албан тушаал (шилжин ажилласан)'),
        ),
        migrations.AlterUniqueTogether(
            name='timesheetentry',
            unique_together={('employee_code', 'year', 'month', 'position_name')},
        ),
    ]
