# Generated by Django 6.0 on 2026-10-01 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_attendance_position_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_additional',
            field=models.BooleanField(default=False, verbose_name='Хавсарсан албан тушаалын мөр'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_additional', False)), fields=('employee_code', 'date'), name='unique_attendance_primary_row'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_additional', True)), fields=('employee_code', 'date', 'position_name'), name='unique_attendance_additional_row'),
        ),
    ]
