# Generated by Django 6.0 on 2026-10-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_attendance_additional_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='deactivated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Идэвхгүй болсон огноо'),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Идэвхтэй'),
        ),
    ]
