# Generated by Django 6.0 on 2026-10-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_meal_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsetting',
            name='card_approver',
            field=models.CharField(blank=True, default='Б.Болор-Эрдэнэ', max_length=100, verbose_name='Картын цалин батлах захирал'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='cash_approver',
            field=models.CharField(blank=True, default='Б.Очгэрэл', max_length=100, verbose_name='Бэлэн цалин батлах захирал'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='company_name',
            field=models.CharField(blank=True, default='Төгс Амин Эрдэнэ ХХК', max_length=200, verbose_name='Байгууллагын нэр'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='prepared_by',
            field=models.CharField(blank=True, default='О.Баяржаргал', max_length=100, verbose_name='Тооцоо гаргасан нягтлан'),
        ),
    ]
