# Generated by Django 6.0 on 2026-10-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_payroll_print_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsetting',
            name='print_columns',
            field=models.JSONField(blank=True, default=dict, verbose_name='Хэвлэх баганууд'),
        ),
    ]
