# Generated by Django 6.0 on 2026-10-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_payroll_print_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayprofile',
            name='cash_bank_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='Бэлэн цалингийн данс'),
        ),
    ]
