# Generated by Django 6.0 on 2026-10-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_employeepayprofile_cash_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsetting',
            name='advance_day',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Урьдчилгаа олгох өдөр'),
        ),
    ]
