# Generated by Django 6.0 on 2026-10-03 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_seed_recpay_report_menu_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesBonusMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50, unique=True, verbose_name='Ажилтны код')),
                ('scheme', models.CharField(choices=[('storekeeper', 'Нярав'), ('sales_rep', 'Худалдааны төлөөлөгч'), ('cash_seller', 'Борлуулагч'), ('distributor', 'Түгээгч')], max_length=20, verbose_name='Нэмэгдлийн хүснэгт')),
                ('channels', models.JSONField(blank=True, default=list, verbose_name='Сувгууд ба хувь')),
                ('source', models.CharField(choices=[('credit', 'Авлагын кредит (сувгаар)'), ('delivery', 'Түгээлт (нийт)')], default='credit', max_length=10, verbose_name='Борлуулалтын суурь')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Дараалал')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
            ],
            options={
                'verbose_name': 'Борлуулалтын нэмэгдлийн ажилтан',
                'verbose_name_plural': 'Борлуулалтын нэмэгдлийн ажилчид',
                'db_table': 'shop_sales_bonus_member',
                'ordering': ['scheme', 'sort_order', 'employee_code'],
            },
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='sales_bonus_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Борлуулалтын нэмэгдлийн тохиргоо'),
        ),
        migrations.CreateModel(
            name='SalesBonusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(db_index=True, max_length=50, verbose_name='Ажилтны код')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Он')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Сар')),
                ('scheme', models.CharField(choices=[('storekeeper', 'Нярав'), ('sales_rep', 'Худалдааны төлөөлөгч'), ('cash_seller', 'Борлуулагч'), ('distributor', 'Түгээгч')], max_length=20, verbose_name='Нэмэгдлийн хүснэгт')),
                ('inputs', models.JSONField(blank=True, default=dict, verbose_name='Оруулсан утгууд')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Борлуулалтын нэмэгдэл')),
                ('card_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Картад')),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Бэлэнд')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Засварласан хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Борлуулалтын нэмэгдлийн бодолт',
                'verbose_name_plural': 'Борлуулалтын нэмэгдлийн бодолтууд',
                'db_table': 'shop_sales_bonus_entry',
                'unique_together': {('employee_code', 'year', 'month')},
            },
        ),
    ]
