# Generated by Django 6.0 on 2026-10-04 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_seed_sales_bonus_menu_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesbonusentry',
            unique_together={('employee_code', 'year', 'month', 'scheme')},
        ),
        migrations.CreateModel(
            name='SalesBonusSubstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Он')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Сар')),
                ('employee_code', models.CharField(max_length=50, verbose_name='Ажилтны код')),
                ('mode', models.CharField(choices=[('replace', 'Орлосон'), ('share', 'Хамт (хуваана)')], default='replace', max_length=10, verbose_name='Хэлбэр')),
                ('dates', models.JSONField(blank=True, default=list, verbose_name='Өдрүүд')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Тайлбар')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Засварласан хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Нярав орлолт',
                'verbose_name_plural': 'Нярав орлолтууд',
                'db_table': 'shop_sales_bonus_substitute',
                'ordering': ['year', 'month', 'id'],
            },
        ),
    ]
