# Generated by Django 6.0 on 2026-10-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_sales_bonus_substitute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbonussubstitute',
            name='mode',
            field=models.CharField(choices=[('replace', 'Орлосон')], default='replace', max_length=10, verbose_name='Хэлбэр'),
        ),
    ]
