# Generated by Django 6.0 on 2026-10-04 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_substitute_replace_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_index=True, max_length=128, verbose_name='Хүснэгт')),
                ('database', models.CharField(blank=True, max_length=128, verbose_name='MSSQL өгөгдлийн сан')),
                ('status', models.CharField(choices=[('running', 'Татаж байна'), ('success', 'Амжилттай'), ('error', 'Алдаа')], default='running', max_length=10, verbose_name='Төлөв')),
                ('rows', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мөрийн тоо')),
                ('seconds', models.FloatField(blank=True, null=True, verbose_name='Хугацаа (сек)')),
                ('message', models.TextField(blank=True, verbose_name='Мессеж')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Эхэлсэн')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дууссан')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Өгөгдөл татсан түүх',
                'verbose_name_plural': 'Өгөгдөл татсан түүх',
                'db_table': 'shop_opendata_sync_log',
                'ordering': ['-started_at'],
            },
        ),
    ]
