# Generated by Django 6.0 on 2026-10-04 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_opendata_sync_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnloadingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, unique=True, verbose_name='Татан авалтын дугаар')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Татан авалтын огноо')),
                ('vendor_name', models.CharField(blank=True, max_length=255, verbose_name='Илгээгч')),
                ('unload_date', models.DateField(db_index=True, verbose_name='Буулгасан огноо')),
                ('fee_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Нэг хүний ажлын хөлс')),
                ('outside_count', models.PositiveSmallIntegerField(default=0, verbose_name='Гаднаас хөлсөлсөн хүний тоо')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Тайлбар')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Засварласан хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Ачаа буулгалт',
                'verbose_name_plural': 'Ачаа буулгалтууд',
                'db_table': 'shop_unloading_event',
                'ordering': ['-unload_date', 'document_number'],
            },
        ),
        migrations.CreateModel(
            name='UnloadingWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(db_index=True, max_length=50, verbose_name='Ажилтны код')),
                ('role', models.CharField(choices=[('customs', 'Гааль мэдүүлсэн'), ('check', 'Хянаж авсан'), ('receive', 'Орлого хүлээж авсан'), ('unload', 'Буулгаж зөөсөн')], default='unload', max_length=10, verbose_name='Үүрэг')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='shop.unloadingevent')),
            ],
            options={
                'verbose_name': 'Ачаа буулгасан ажилтан',
                'verbose_name_plural': 'Ачаа буулгасан ажилчид',
                'db_table': 'shop_unloading_worker',
                'unique_together': {('event', 'employee_code')},
            },
        ),
    ]
