# Generated by Django 6.0 on 2026-10-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_unloadingevent_document_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnloadingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customs_code', models.CharField(blank=True, max_length=50, verbose_name='Гааль мэдүүлэх ажилтан')),
                ('check_code', models.CharField(blank=True, max_length=50, verbose_name='Хянаж авах ажилтан')),
                ('receive_code', models.CharField(blank=True, max_length=50, verbose_name='Орлого хүлээж авах ажилтан')),
                ('key_fee', models.DecimalField(decimal_places=2, default=100000, max_digits=14, verbose_name='Гааль/хяналт/орлогын хүний хөлс')),
                ('worker_fee', models.DecimalField(decimal_places=2, default=60000, max_digits=14, verbose_name='Бусад ажилтны хөлс')),
                ('outside_fee', models.DecimalField(decimal_places=2, default=80000, max_digits=14, verbose_name='Гаднаас хөлсөлсөн хүний хөлс')),
            ],
            options={
                'verbose_name': 'Ачаа буулгалтын тохиргоо',
                'verbose_name_plural': 'Ачаа буулгалтын тохиргоо',
                'db_table': 'shop_unloading_settings',
            },
        ),
        migrations.RemoveField(
            model_name='unloadingevent',
            name='fee_per_person',
        ),
        migrations.AddField(
            model_name='unloadingevent',
            name='outside_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Гаднаас хөлсөлсөн нэг хүний хөлс'),
        ),
        migrations.AddField(
            model_name='unloadingworker',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Ажлын хөлс'),
        ),
    ]
