# Generated by Django 6.0 on 2026-10-05 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_attendancepositionrule_no_transport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesBonusMonthMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Он')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Сар')),
                ('scheme', models.CharField(choices=[('storekeeper', 'Нярав'), ('sales_rep', 'Худалдааны төлөөлөгч'), ('cash_seller', 'Борлуулагч'), ('distributor', 'Түгээгч')], max_length=20, verbose_name='Нэмэгдлийн хүснэгт')),
                ('employee_code', models.CharField(max_length=50, verbose_name='Ажилтны код')),
                ('excluded', models.BooleanField(default=False, verbose_name='Хассан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Засварласан хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Сарын нэмэгдлийн ажилтан (нэмсэн/хассан)',
                'verbose_name_plural': 'Сарын нэмэгдлийн ажилчид (нэмсэн/хассан)',
                'db_table': 'shop_sales_bonus_month_member',
                'unique_together': {('year', 'month', 'scheme', 'employee_code')},
            },
        ),
    ]
