# Generated by Django 6.0 on 2026-10-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_salesbonusmonthmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='saturday_bonus_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Бямбад ажилласан нэмэгдэл (гараар)'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='transport_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Унааны мөнгө (гараар)'),
        ),
    ]
