# Generated by Django 6.0.8 on 2026-10-06 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_seed_my_payroll_menu_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollMonthClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Он')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Сар')),
                ('sheet', models.CharField(choices=[('card', 'Карт'), ('cash', 'Бэлэн')], max_length=10, verbose_name='Хуудас')),
                ('rows', models.JSONField(default=list, verbose_name='Бодогдсон мөрүүд')),
                ('closed_at', models.DateTimeField(auto_now=True, verbose_name='Хаасан огноо')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хаасан хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Хаагдсан сарын цалин',
                'verbose_name_plural': 'Хаагдсан сарын цалингууд',
                'db_table': 'shop_payroll_month_close',
                'unique_together': {('year', 'month', 'sheet')},
            },
        ),
    ]
