# Generated by Django 6.0.8 on 2026-10-06 06:05

from django.db import migrations, models


def seed_menu(apps, schema_editor):
    """Хувийн мэдээлэл - "Борлуулалтын нэмэгдэл" цэсийг Алтжин худалдагчид нээнэ ("Миний мэдээлэл" харагддаг бол)."""
    MenuPermission = apps.get_model('shop', 'MenuPermission')
    if MenuPermission.objects.filter(position_name='Алтжин худалдагч', menu_key='profile', is_visible=True).exists():
        MenuPermission.objects.get_or_create(
            position_name='Алтжин худалдагч', menu_key='my_sales_bonus', defaults={'is_visible': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_seed_payroll_report_menu_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbonusentry',
            name='scheme',
            field=models.CharField(choices=[('storekeeper', 'Нярав'), ('sales_rep', 'Худалдааны төлөөлөгч'), ('cash_seller', 'Борлуулагч'), ('distributor', 'Түгээгч'), ('altjin_seller', 'Алтжин худалдагч')], max_length=20, verbose_name='Нэмэгдлийн хүснэгт'),
        ),
        migrations.AlterField(
            model_name='salesbonusmember',
            name='scheme',
            field=models.CharField(choices=[('storekeeper', 'Нярав'), ('sales_rep', 'Худалдааны төлөөлөгч'), ('cash_seller', 'Борлуулагч'), ('distributor', 'Түгээгч'), ('altjin_seller', 'Алтжин худалдагч')], max_length=20, verbose_name='Нэмэгдлийн хүснэгт'),
        ),
        migrations.AlterField(
            model_name='salesbonusmonthmember',
            name='scheme',
            field=models.CharField(choices=[('storekeeper', 'Нярав'), ('sales_rep', 'Худалдааны төлөөлөгч'), ('cash_seller', 'Борлуулагч'), ('distributor', 'Түгээгч'), ('altjin_seller', 'Алтжин худалдагч')], max_length=20, verbose_name='Нэмэгдлийн хүснэгт'),
        ),
        migrations.RunPython(seed_menu, migrations.RunPython.noop),
    ]
